version: '2'
services:
  electionvue-app:
    image: electionvue
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://electionvue-postgresql:5432/electionvue
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  electionvue-postgresql:
    extends:
      file: postgresql.yml
      service: electionvue-postgresql
